const cron = require("node-cron");
const { MessageMedia } = require("whatsapp-web.js");
const { autoGeneratedText } = require("./messageTemplates");
const sendMessageToGroup = async (client, message) => {
  const grpchat = await client.getChatById(ourGroupId);
  let text = `${message}\n`;
  let mentions = [];
  console.log(grpchat);
  for (let participant of grpchat.participants) {
    const contact = await client.getContactById(participant.id._serialized);
    mentions.push(contact);
    text += `@${participant.id.user} `;
  }
  await grpchat.sendMessage(text, { mentions });
};

const initCronJobs = (client) => {
  //send message after every hour
  cron.schedule(
    "0 20 * * 3",
    () => {
      console.log("wednesday");
      const media = MessageMedia.fromFilePath("./already_wednesday.jpeg");

      client.sendMessage("923470545035-1624354694@g.us", media, {
        caption: autoGeneratedText,
      });
      client.sendMessage("923045032467@c.us", media, {
        caption: autoGeneratedText,
      });
    },
    {
      timezone: "Asia/Karachi",
    }
  );
  cron.schedule("0 */1 * * *", () => {
    client.sendMessage("923045032467@c.us", "Your bot is running!");
  });
  cron.schedule(
    "0 0 * * *",
    () => {
      sendMessageToGroup(client, goodNightMessage);
      console.log("hello");
    },
    {
      timezone: "Asia/Karachi",
    }
  );
  cron.schedule(
    "0 10 * * *",
    () => sendMessageToGroup(client, goodMorningMessage),
    {
      timezone: "Asia/Karachi",
    }
  );
};

module.exports = initCronJobs;
