const ourGroupId = "923054496675-1537473829@g.us";
const AbdullahJauhar = "923164954392@c.us";
const autoGeneratedText =
  "\n\n\n[ This is an Auto-generated Text ]\n" + "[ reply-bot by sameer]\n";

const goodNightMessage = "Good Night! \n\n [via night-cron-job]";
const goodMorningMessage = "Good Morning! \n\n [via morning-cron-job]";

module.exports = {
  ourGroupId,
  AbdullahJauhar,
  autoGeneratedText,
  goodMorningMessage,
  goodNightMessage,
};
