const { Client, LocalAuth } = require("whatsapp-web.js");
const initCronJobs = require("./cronJobs");
const { autoGeneratedText } = require("./messageTemplates");
const client = new Client({
  restartOnAuthFail: true,
  puppeteer: {
    headless: true,
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-accelerated-2d-canvas",
      "--no-first-run",
      "--no-zygote",
      "--single-process", // <- this one doesn't works in Windows
      "--disable-gpu",
    ],
  },
  authStrategy: new LocalAuth({ dataPath: "reply-bot-wa2" }),
});

const createClient = () => {
  client.on("ready", () => {
    console.log(`Client Ready!`);
    client.sendMessage("923045032467@c.us", "Client started!");
    initCronJobs(client);
  });

  client.on("authenticated", () => {
    console.log("AUTHENTICATED");
  });

  client.on("message", async (message) => {
    console.log(`CHAT_ID: ${message.from}, AUTHOR: ${message.author}`);
    const messageText = message.body.toLowerCase();
    if (messageText.includes("eid") && messageText.includes("mubarak")) {
      const newMessage = "Khair Mubarak!\n" + autoGeneratedText;
      message.reply(newMessage);
    }
  });
  return client;
};

module.exports = createClient;
